language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode10

env:
  global:
    - QPMX_CACHE_DIR=$HOME/.qpmx-cache  # needs to be set for ci scripts
    - QT_VER=5.11.2
    - DOCKER_IMAGE=common
    - QMAKE_FLAGS="PREFIX=/"
    - NO_TESTS=true
    - EXTRA_MODULES=".skycoder42.jsonserializer"

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
    - os: osx
      env:
        - PLATFORM=clang_64

before_install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - if [ "$PLATFORM" == "gcc_64" ]; then ./ci/travis_init.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh; else ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh; fi

script:
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh
  - if [ "$PLATFORM" != "gcc_64" ]; then ./ci/travis_test.sh sudo; fi
