image:
  - Visual Studio 2017

version: build-{build}

environment:
  QT_VER: 5.11.2
  EXTRA_MODULES: .skycoder42.jsonserializer
  QMAKE_FLAGS: "PREFIX=/deploy"
  NO_TESTS: true
  PREFIX: \

  matrix:
    - PLATFORM: msvc2017_64
#    - PLATFORM: mingw53_32

install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat

after_build:
  - .\ci\appveyor_test.bat
  - .\ci\appveyor_deploy.bat

artifacts:
  - path: install\qpmx-*.zip

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*/
  force_update: false
  on:
    appveyor_repo_tag: true

