image:
  - Visual Studio 2017

version: build-{build}

environment:
  QT_VER: 5.9.2
  PLATFORM: msvc2017_64
  EXTRA_MODULES: .skycoder42.jsonserializer
  NO_TESTS: true

install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat
  - .\ci\appveyor_test.bat

artifacts:
  - path: install\repository_win.zip
  - path: install\qpmx Installer.exe

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*/
  force_update: false
  on:
    appveyor_repo_tag: true

