image:
  - Visual Studio 2017
#  - Visual Studio 2015

version: build-{build}

environment:
  QT_VER: 5.10.1
  EXTRA_MODULES: .skycoder42.jsonserializer
  NO_TESTS: true
  PREFIX: \

  matrix:
    - PLATFORM: msvc2017_64
#    - PLATFORM: mingw53_32

#matrix:
#  exclude:
#    - PLATFORM: msvc2017_64
#      image: Visual Studio 2015
#    - PLATFORM: mingw53_32
#      image: Visual Studio 2017

install:
  - git submodule init
  - git submodule update
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat

after_build:
  - .\ci\appveyor_test.bat
  - .\ci\appveyor_deploy.bat

artifacts:
  - path: install
    name: qpmx_win_deployed
    type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*/
  force_update: false
  on:
    appveyor_repo_tag: true

