isEmpty($$PREFIX) {
	PREFIX= $$[QT_INSTALL_PREFIX]
	INSTALL_BINS = $$[QT_INSTALL_BINS]
	INSTALL_HEADERS = $$[QT_INSTALL_HEADERS]
	INSTALL_PLUGINS = $$[QT_INSTALL_PLUGINS]
	INSTALL_SHARE = $${PREFIX}/share
} else {
	isEmpty($$INSTALL_BINS): INSTALL_BINS = $${PREFIX}/bin
	isEmpty($$INSTALL_HEADERS): INSTALL_HEADERS = $${PREFIX}/include
	isEmpty($$INSTALL_PLUGINS): INSTALL_BINS = $${PREFIX}/plugins
	isEmpty($$INSTALL_SHARE): INSTALL_SHARE = $${PREFIX}/share
}
